# Generated by Django 2.1.5 on 2019-04-27 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdl_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_id', models.IntegerField(default=0)),
                ('prj_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mdl_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_name', models.CharField(max_length=200)),
                ('tsk_date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date start')),
                ('tsk_date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date end')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mdl_Project')),
            ],
        ),
    ]
