# Generated by Django 2.1.5 on 2019-05-02 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mdl_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Waiting', 'Waiting'), ('Working', 'Working'), ('completed', 'completed'), ('discontinued', 'discontinued'), ('pending', 'pending')], max_length=10, null=True)),
                ('note', models.CharField(max_length=500, null=True)),
                ('member', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mdl_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='date start')),
                ('end', models.DateField(default=django.utils.timezone.now, verbose_name='date end')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mdl_Project')),
            ],
        ),
    ]
